name: face_recognition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - tensorflow==2.16.1
      - opencv-python
      - matplotlib
      - numpy
      - fastapi
      - uvicorn
      - httpx
      - python-multipart
      - kivy
